### ISSUE TITLE
QQ消息推送中的链接处理问题

### ISSUE THREAD

**Issue by fa93hws** [fa93hws/snowball-rss#88]
## 问题描述
当时设计的时候，考虑到发送敏感信息会被腾讯冻结一天以上，因此没有对文字做转发处理，而只是简单的截图而已。但是当内容中有链接时，用户体验会比较差。
![image](https://user-images.githubusercontent.com/10626756/147613401-dc27785f-4c04-488f-b948-30de7d003fb4.png)

## 解决方案
依旧不发文字，防止机器人被冻结。但是链接会附在转发内容中。比如
```
盛京剑客发布了一条新消息
https://xueqiu.com/6784593966/207283854
监测到原文中有链接，以此为
https://xueqiu.com/6784593966/xxx
https://xueqiu.com/6784593966/yyy
截图发送中
```

**Comment by applo-susheng** [comment]
赞成此方案
